### ISSUE TITLE
gdb-token-authentication: token not refreshed after GraphDB Server restarted

### ISSUE THREAD

**Issue by LesterLyu** [Ontotext-AD/graphdb.js#197] opened 2024-01-24 18:04 UTC
**Library version [3.0.1]**

**Node.js version [18]**

**Describe the bug**
When using GdbTokenAuthentication, request cannot be made after GraphDB server restart.

```js
const config = new RepositoryClientConfig(endpoint)
  .setEndpoints(endpoints)
  .setHeaders(headers)
  .setDefaultRDFMimeType(contentType)
  .setReadTimeout(readTimeout)
  .setWriteTimeout(writeTimeout)
  .useGdbTokenAuthentication('testuser', 'pass123');
```

`config.useBasicAuthentication('testuser', 'pass123')` requests works after GraphDB server restart.

**Comment by DesiBorisova** [comment] 2024-02-07 13:39
Hello @LesterLyu. I'm not able to reproduce this behavior. I tested with the following:

```
const repositoryClientConfig = new RepositoryClientConfig(endpoint)
    .setEndpoints(endpoints)
    .setHeaders(headers)
    .setDefaultRDFMimeType('')
    .setReadTimeout(3000)
    .setWriteTimeout(3000)
    .useGdbTokenAuthentication('admin', 'root');
const rdfRepositoryClient = new RDFRepositoryClient(repositoryClientConfig);
```

Getting the repository size:
```
try {
         const clientRepoSize = await rdfRepositoryClient.getSize();
         console.log(clientRepoSize);
     } catch (e) {
         console.error(e);
     }
```
     
Getting the namespaces:
```
return rdfRepositoryClient.getNamespaces().then((namespaces) => {
            namespaces.forEach((namespace) => {
                console.log(namespace.getPrefix() + ' -> ' + namespace.getNamespace());
            });
```
            
Executing a sparql update query
```
const payload = new UpdateQueryPayload()
        .setQuery('INSERT {?s ?p ?o} WHERE {?s ?p ?o}')
        .setContentType(X_WWW_FORM_URLENCODED)
        .setInference(true)
        .setTimeout(5);

    return rdfRepositoryClient.update(payload).then(() => {
        console.log('updated');
    });
```
    
These all ran successfully. I restarted the GraphDB server and ran them again, without issues. Could you please confirm if your setup is the same?

**Comment by LesterLyu** [comment] 2024-02-07 16:16
Sorry, I didn't make it clear.

This happened in a backend server, where it keeps running for api requests. If the GraphDB server is restarted while the backend server is running (no requests are being made during the restart), graphdb.js will fail to get a new token upon making a request after the restart.

This could be simulated by
```js
const repositoryClientConfig = new RepositoryClientConfig(endpoint)
    .setEndpoints(endpoints)
    .setHeaders(headers)
    .setDefaultRDFMimeType('')
    .setReadTimeout(3000)
    .setWriteTimeout(3000)
    .useGdbTokenAuthentication('admin', 'root');
const rdfRepositoryClient = new RDFRepositoryClient(repositoryClientConfig);

const payload = new UpdateQueryPayload()
        .setQuery('INSERT {?s ?p ?o} WHERE {?s ?p ?o}')
        .setContentType(X_WWW_FORM_URLENCODED)
        .setInference(true)
        .setTimeout(5);

await rdfRepositoryClient.update(payload)


// Now restart the GraphDB server within the 20 seconds sleep
await new Promise((resolve) => setTimeout(resolve, 20000));

const payload = new UpdateQueryPayload()
        .setQuery('INSERT {?s ?p ?o} WHERE {?s ?p ?o}')
        .setContentType(X_WWW_FORM_URLENCODED)
        .setInference(true)
        .setTimeout(5);

await rdfRepositoryClient.update(payload);
```

**Comment by svilenvelikov** [comment] 2024-02-09 14:16
@LesterLyu Thank you for the report. We found where is the problem. It appears that there is a bug in BaseRepositoryClient which will be fixed and a new patch release will be published.

**Comment by DesiBorisova** [comment] 2024-02-14 08:20
@LesterLyu the new patch release has been published and contains the fix for this bug.

**Closed by DesiBorisova** 2024-02-14 08:20 UTC
Labels: bug
